## 1. Reminders and generalities on Grothendieck groups {#IV.1}

::: {.rmenv #IV.1.1 title="1.1" latex="{1.1}"}
\oldpage{1 (274)}Let $\cal{C}$ be a *triangulated* category.
Recall ([I 6.3](#I.6.3) and [SGA 5 VIII 2]) that a map $f$ from $\ob\cal{C}$ to an abelian group $G$ is said to be *additive* if we have $f(E)=f(E')+f(E'')$ for every distinguished triangle $E'\to E\to E''\to E'[1]$.
The additive maps from $\ob\cal{C}$ to $G$ form an abelian group, which depends functorially on $G$.
The functor thus obtained is represented by an abelian group $k(\cal{C})$ and a universal additive map $\cl\colon\ob\cal{C}\to k(\cal{C})$ (denoted by $\cl$ when there is no risk of confusion).

The group $k(\cal{C})$ depends functorially on $\cal{C}$ with respect to exact functors.
If $\cal{C}$ and $\cal{C}'$ are triangulated categories, then any two isomorphic exact functors from $\cal{C}$ to $\cal{C}'$ induce the same homomorphism $k(\cal{C})\to k(\cal{C}')$;
in particular, if $u\colon\cal{C}\to\cal{C}'$ is an exact functor that is an equivalence of categories, then $k(u)\colon k(\cal{C})\to k(\cal{C}')$ is an isomorphism.
:::

::: {.itenv #IV.1.2 title="Lemma 1.2" latex="{Lemma 1.2}"}
Let $\cal{C}$ be a triangulated category, and $L\in\ob\cal{C}$.

a. For every $n\in\mathbb{Z}$, we have
  $$
    \cl(L[n])
    = (-1)^n\cl(L).
  $$
  If $L'$ and $L''$ are objects of $\cal{C}$ such that we have $L\cong L'\oplus L''$, then we have
  $$
    \cl(L)
    = \cl(L') + \cl(L'').
  $$
b. Suppose that there exists $n\in\mathbb{Z}$ such that $\coprod_{i\geq0}L[2ni]$ is representable.
  Then $\cl(L)=0$.
:::

::: {.proof}
Claim (a) follows directly from the definitions (cf. [SGA 5 VIII 2]).
For (b), it suffices to remark that we have
$$
  \coprod_{i\geq0} L[2ni]
  \cong L\oplus\left(\coprod_{i\geq0} L[2ni]\right)[2n]
$$
\oldpage{2 (275)}and to apply (a).
:::

::: {.itenv #IV.1.3 title="Lemma 1.3" latex="{Lemma 1.3}"}
Let $\cal{C}$ be a triangulated category, and $\cal{A}$ a thick subcategory ([@IV-V, I 2.1]).
Then the inclusion and passage to the quotient functors define an exact sequence
$$
  k(\cal{A})
  \to k(\cal{C})
  \to k(\cal{C}/\cal{A})
  \to 0.
$$
:::

::: {.proof}
See [SGA 5 VIII 3.1].
:::

::: {.itenv #IV.1.4 title="Lemma 1.4" latex="{Lemma 1.4}"}
Let $\cal{A}$ be an additive (resp. abelian) category, and $f$ an additive function ([1.1](#IV.1.1)) on $\ob\Kb(A)$ (resp. $\Db(A)$).
For $E\in\ob\Kb(A)$ (resp. $\Db(A)$) we have
$$
  f(E)
  = \sum (-1)^i f(E^i)
$$
(resp. $f(E)=\sum(-1)^i f(\HH^i(E))$).
:::

::: {.proof}
Left as an exercise to the reader.
:::

::: {.rmenv #IV.1.5 title="1.5" latex="{1.5}"}
Let
:::
