--- 
title: "Étale covers and the fundamental group (SGA 1)"
author: "A. Grothendieck and M. Raynaud"
date: "1960--1961 (web version last updated: `r format(Sys.Date(), format='%d %B %Y')`)"
description: "Séminaire de Géométrie Algébrique du Bois Marie: Book 1."
output:
  bookdown::gitbook:
    config:
      toc:
        before: |
          <li><a href="../">SGA</a>/SGA 1</li>
---

\renewcommand{\leq}{\leqslant}
\renewcommand{\geq}{\geqslant}
\renewcommand{\hat}{\widehat}
\renewcommand{\tilde}{\widetilde}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}

\providecommand{\alg}[1]{#1\mathsf{-alg}}

\providecommand{\tr}{\operatorname{tr}}
\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\gr}{\operatorname{gr}}
\providecommand{\rank}{\operatorname{rank}}
\providecommand{\id}{\mathrm{id}}
\providecommand{\dd}{\mathrm{d}}

# Introduction {-}

In the first section of this introduction, we give some details about the contents of the present volume;
\oldpage{vii}
in the second, about the entirety of the "_Séminaire de Géométrie Algébrique du Bois-Marie_", of which the present volume constitutes the first tome.

## 1.

The present volume details the fundamentals of a theory of the fundamental group in algebraic geometry, from the "Kroneckerian" point of view, which allows us to treat the case of an algebraic variety, in the usual sense, and that of a ring of integers of a number field, for example, on an equal footing.
This point of view can only be expressed in a satisfactory manner in the language of schemes, and we will freely use this language, as well as the main results stated in the first three chapters of the _Éléments de Géométrie Algébrique_ by J. Dieudonné and A. Grothendieck (cited as "EGA").
The study of this present volume of the "_Séminaire de Géométrie Algébrique du Bois-Marie_" does not require any other knowledge of algebraic geometry, and can thus serve as an introduction to the current techniques of algebraic geometry, to a reader who wishes to familiarise themselves with these techniques.

Chapters I to XI of this book are a textual reproduction, practically unchanged, of the mimeographed notes from the oral seminar, which where distributed by the _Institut des Hautes Études Scientifiques_.^[As well as the notes of the following seminars. Since this method of distribution turned out to be impractical and inadequate in the long term, all the "_Séminaire de Géométrie Algébrique du Bois-Marie_" from now on will appear in book form, like the present volume.]
We have restricted ourselves to adding some footnotes to the original text, correcting typos, and making an adjustment to terminology (notably, "simple morphism" being replaced with "smooth morphism", which does not lead to the same confusion).

\oldpage{viii}

Chapters I to IV present the local notions of _étale_ and _smooth_ morphisms;
they hardly ever use the language of schemes, as detailed in Chapter I of the _Élements_.^[A more complete study is now available in the _Élements_, Chapter IV, §§17 and 18]
Chapter V presents the axiomatic description of the fundamental group of a scheme, which is useful even in the classical case, where the scheme is simply the spectrum of a field, since we then find a strong and convenient reformulation of the usual Galois theory.
Chapters VI and VIII present the _theory of descent_, which has become more and more important in algebraic geometry over the past few years, and which could do the same in analytic geometry and in topology.
We note that Chapter VII was not transcribed, but its contents can be found incorporated into an article by J. Giraud ("Méthode de la Descente", _Bull. Soc. Math. France_ **2** (1964), viii + 150 p.).
In chapter IX, we study more specifically the theory of descent by étale morphisms, obtaining a systematic approach for Van Kampen type theorems for the fundamental group, which appear here as simple translations of theorems of descent.
It essentially deals with a calculation of the fundamental group of a connected scheme $X$ endowed with a surjective and proper morphism (say, $X'\to X$) in terms of the fundamental groups of the connected components of $X'$ and of the fibre products $X'\times_X X'$, $X'\times_X X'\times_X X'$, and the homomorphisms between these groups induced by the canonical simplicial morphisms between the above schemes.
Chapter X gives the theory of _specialisation of the fundamental group_ for a proper and smooth morphism, with the most striking result being the determination (more or less) of the fundamental group of a smooth algebraic curve in characteristic $p>0$, thanks to the known result obtained by transcendental methods in characteristic zero.
Chapter XI gives some examples and addenda, including a cohomological version of Kummer's theory of coverings, as well as Artin--Schreier's.
For other commentaries on the text, see the [_Foreword_](#foreword), found after this introduction.

Since the editing of the seminar in 1961, the language of _étale topology_, along with a corresponding cohomology theory, has been developed by M. Artin in collaboration with myself;
it is detailed in SGA 4 ("Cohomologie étale des schémes") of the _Séminaire de Géométrie Algébrique_, which will appear in the same series as the present volume.
This language, as well as the results that it has given up until now, give us a particularly supple tool for the study of the fundamental group, allowing us to better understand (and even improve upon) certain results given here.
There will thus be a need to entirely rewrite the theory of the fundamental group from this point of view (in fact, all the key results so far appear in _loc. cit._).
This was what was planed for the chapter of _Élements_ dedicated to the fundamental group, which also had to cover many other ideas which could not find their place here (relying on the technique of resolution of singularities):
\oldpage{ix}
calculation of the "local fundamental group" of a complete local ring in terms of a suitable resolution of singularities of the ring, local and global Künneth formulas for the fundamental group without any hypotheses of properness (cf. [Exp. XIII](#XIII)), the results of M. Artin on the comparison of the local fundamental groups of an excellent Henselian local ring and of its completion (SGA 4 XIX).
We also note the necessity of developing a theory of the fundamental group of a topos, which would simultaneously cover the ordinary topological theory, the semi-simplicial version, the "profinite" version developed in [Exp. V](#V), and the slightly more general pro-discrete version found in SGA 3 X 7 (adapted to the case of non-normal and non-unibranch schemes).
While we wait for such a rewriting of the whole theory, [Exp. XIII](#XIII), by Mme Raynaud, using the language and results of SGA 4, aims to show the part that we can extract in some typical questions, most notably generalising certain results of [Exp. X](#XIII) to non-proper relative schemes.
There we give, in particular, the structure of the "prime at $p$" fundamental group of a non-complete algebraic curve in arbitrary characteristic (which I announced in 1959, but for which a proof had not been published up until now).

Despite these numerous gaps and imperfections (as others would say: because of these gaps and imperfections), I think that the present volume could be useful for the reader who wishes to familiarise themselves with the theory of the fundamental group, as well as a work of reference, as we await the editing and appearance of a text that avoids the criticisms that I have just listed.


## 2.

The present volume constitutes the tome 1 of the "_Séminaire de Géométrie Algébrique du Bois-Marie_", whose following volumes are intended to appear in the same series as this one.
The aim of the _Séminaire_, parallel to the "_Éléments de Géométrie Algébrique_" by J. Dieudonné and A. Grothendieck, is to establish the fundamentals of algebraic geometry, following the points of view of the latter.
The standard reference for all the volumes of the _Séminaire_ consists of Chapters I, II, and III of "_Éléments de Géométrie Algébrique_" (cited as EGA I, II, and III), and we assume the reader to be have the education in commutative algebra and homological algebra that these chapters imply.^[See the Introduction of EGA I for more precise details.]
Furthermore, in each volume of the _Séminaire_, we will freely refer, as needed, to previous volumes of the same _Séminaire_, or to other chapters of "_Élements_", either already published or on the brink of being published.

Each _volume_ of the _Séminaire_ is based on a main subject, indicated in the title of the corresponding volume(s);
the oral seminar generally lasts one academic year, sometimes more.
The exposés within each volume of the _Séminaire_ are generally in a logical order of dependence on one another;
however, the different volumes of the _Séminaire_ are largely logically independent of one another.
\oldpage{x}
So the volume "Group schemes" is largely logically independent of the two volumes of the _Séminaire_ that come before it chronologically;
however, it makes frequent reference to results of EGA IV.
Here is the list of the volumes of the _Séminaire_ that should appear (cited as SGA I to SGA 7 in what follows):

- SGA 1. Étale covers and the fundamental group, 1960/61.
- SGA 2. Local cohomology of coherent sheaves and local and global Lefschetz theorems, 1961/62.
- SGA 3. Group schemes, 1963/64 (3 volumes, in collaboration with M. Demazure).
- SGA 4. Topos theory and étale cohomology of schemes, 1963/64 (3 volumes, in collaboration with M. Artin and J.L. Verdier).
- SGA 5. $\ell$-adic cohomology and $L$-functions, 1964/65 (2 volumes).
- SGA 6. Intersection theory and the Riemann--Roch theorem, 1966/67 (2 volumes, in collaboration with P. Berthelot and L. Illusie).
- SGA 7. Local monodromy groups in algebraic geometry.

Three of these partial _Séminaires_ have been written in _collaboration_ with other mathematicians, who appear as coauthors on the covers of the corresponding volumes.
As for the other active participants of the _Séminaire_, whose roles (from as much of an editorial point of view as a mathematical one) have grown over the years, the name of each participant appears at the top of the exposés for which they are responsible, either as speaker or as editor, and the list of those who appear in a given volume can be found on the flyleaf of the volume in question.

**TO-DO**


# Foreword {#foreword}

**TO-DO**