--- 
title: "SGA 1: Étale covers and the fundamental group"
author: "Organised by A. Grothendieck; supplemented by Mme. M. Raynaud"
date: "1960--1961 (web version last updated: `r format(Sys.Date(), format='%d %B %Y')`)"
description: "Séminaire de Géométrie Algébrique du Bois Marie: Book 1."
---

\renewcommand{\leq}{\leqslant}
\renewcommand{\geq}{\geqslant}
\renewcommand{\hat}{\widehat}
\renewcommand{\tilde}{\widetilde}
\renewcommand{\cal}[1]{{\mathcal{#1}}}
\renewcommand{\scr}[1]{{\mathscr{#1}}}
\renewcommand{\frak}[1]{{\mathfrak{#1}}}

\providecommand{\alg}[1]{#1\mathsf{-alg}}

\providecommand{\tr}{\operatorname{tr}}
\providecommand{\Spec}{\operatorname{Spec}}
\providecommand{\Hom}{\operatorname{Hom}}
\providecommand{\gr}{\operatorname{gr}}
\providecommand{\rank}{\operatorname{rank}}
\providecommand{\id}{\mathrm{id}}
\providecommand{\dd}{\mathrm{d}}

# Introduction {-}

In the first section of this introduction, we give some details about the contents of the present volume;
\oldpage{vii}
in the second, about the entirety of the "*Séminaire de Géométrie Algébrique du Bois-Marie*", of which the present volume constitutes the first tome.

## 1. {#introduction.1}

The present volume details the fundamentals of a theory of the fundamental group in algebraic geometry, from the "Kroneckerian" point of view, which allows us to treat the case of an algebraic variety, in the usual sense, and that of a ring of integers of a number field, for example, on an equal footing.
This point of view can only be expressed in a satisfactory manner in the language of schemes, and we will freely use this language, as well as the main results stated in the first three chapters of the *Éléments de Géométrie Algébrique* by J. Dieudonné and A. Grothendieck (cited as "EGA").
The study of this present volume of the "*Séminaire de Géométrie Algébrique du Bois-Marie*" does not require any other knowledge of algebraic geometry, and can thus serve as an introduction to the current techniques of algebraic geometry, to a reader who wishes to familiarise themselves with these techniques.

Exposés I to XI of this book are a textual reproduction, practically unchanged, of the mimeographed notes from the oral seminar, which where distributed by the *Institut des Hautes Études Scientifiques*.^[As well as the notes of the following seminars. Since this method of distribution turned out to be impractical and inadequate in the long term, all the "*Séminaire de Géométrie Algébrique du Bois-Marie*" from now on will appear in book form, like the present volume.]
We have restricted ourselves to adding some footnotes to the original text, correcting typos, and making an adjustment to terminology (notably, "simple morphism" being replaced with "smooth morphism", which does not lead to the same confusion).

\oldpage{viii}

Exposés [I](#I) to [IV](#IV) present the local notions of *étale* and *smooth* morphisms;
they hardly ever use the language of schemes, as detailed in Chapter I of the *Éléments*.^[A more complete study is now available in EGA IV 17,18.]
[Exposé V](#V) presents the axiomatic description of the fundamental group of a scheme, which is useful even in the classical case, where the scheme is simply the spectrum of a field, since we then find a strong and convenient reformulation of the usual Galois theory.
Exposés [VI](#VI) and [VIII](#VIII) present the *theory of descent*, which has become more and more important in algebraic geometry over the past few years, and which could do the same in analytic geometry and in topology.
We note that Exposé VII was not transcribed, but its contents can be found incorporated into an article by J. Giraud ("Méthode de la Descente". *Bull. Soc. Math. France* **2** (1964), viii + 150 p.).
In [Exposé IX](#IX), we study more specifically the theory of descent by étale morphisms, obtaining a systematic approach for Van Kampen type theorems for the fundamental group, which appear here as simple translations of theorems of descent.
It essentially deals with a calculation of the fundamental group of a connected scheme $X$ endowed with a surjective and proper morphism (say, $X'\to X$) in terms of the fundamental groups of the connected components of $X'$ and of the fibre products $X'\times_X X'$, $X'\times_X X'\times_X X'$, and the homomorphisms between these groups induced by the canonical simplicial morphisms between the above schemes.
[Exposé X](#X) gives the theory of *specialisation of the fundamental group* for a proper and smooth morphism, with the most striking result being the determination (more or less) of the fundamental group of a smooth algebraic curve in characteristic $p>0$, thanks to the known result obtained by transcendental methods in characteristic zero.
[Exposé XI](#XI) gives some examples and addenda, including a cohomological version of Kummer's theory of coverings, as well as Artin--Schreier's.
For other commentaries on the text, see the [*Foreword*](#foreword), found after this introduction.

Since the writing of the seminar in 1961, the language of *étale topology*, along with a corresponding cohomology theory, has been developed by M. Artin in collaboration with myself;
it is detailed in SGA 4 ("Cohomologie étale des schémas") of the *Séminaire de Géométrie Algébrique*, which will appear in the same series as the present volume.
This language, as well as the results that it has given up until now, give us a particularly supple tool for the study of the fundamental group, allowing us to better understand (and even improve upon) certain results given here.
There will thus be a need to entirely rewrite the theory of the fundamental group from this point of view (in fact, all the key results so far appear in *loc. cit.*).
This was what was planed for the chapter of *Éléments* dedicated to the fundamental group, which also had to cover many other ideas which could not find their place here (relying on the technique of resolution of singularities):
\oldpage{ix}
calculation of the "local fundamental group" of a complete local ring in terms of a suitable resolution of singularities of the ring, local and global Künneth formulas for the fundamental group without any hypotheses of properness (cf. [Exposé XIII](#XIII)), the results of M. Artin on the comparison of the local fundamental groups of an excellent Henselian local ring and of its completion ([SGA 4 XIX](../SGA-4-3/XIX.html)).
We also note the necessity of developing a theory of the fundamental group of a topos, which would simultaneously cover the ordinary topological theory, the semi-simplicial version, the "profinite" version developed in [Exposé V](#V), and the slightly more general pro-discrete version found in [SGA 3 X 7](../SGA-3-2/X.html#X.7) (adapted to the case of non-normal and non-unibranch schemes).
While we wait for such a rewriting of the whole theory, [Exposé XIII](#XIII), by Mme Raynaud, using the language and results of SGA 4, aims to show the part that we can extract in some typical questions, most notably generalising certain results of [Exposé X](#XIII) to non-proper relative schemes.
There we give, in particular, the structure of the "prime at $p$" fundamental group of a non-complete algebraic curve in arbitrary characteristic (which I announced in 1959, but for which a proof had not been published up until now).

Despite these numerous gaps and imperfections (as others would say: because of these gaps and imperfections), I think that the present volume could be useful for the reader who wishes to familiarise themselves with the theory of the fundamental group, as well as a work of reference, as we await the writing and appearance of a text that avoids the criticisms that I have just listed.


## 2. {#introduction.2}

The present volume constitutes tome 1 of the "*Séminaire de Géométrie Algébrique du Bois-Marie*", whose following volumes are intended to appear in the same series as this one.
The aim of the *Séminaire*, parallel to the "*Éléments de Géométrie Algébrique*" by J. Dieudonné and A. Grothendieck, is to establish the fundamentals of algebraic geometry, following the points of view of the latter.
The standard reference for all the volumes of the *Séminaire* consists of Chapters I, II, and III of "*Éléments de Géométrie Algébrique*" (cited as EGA I, II, and III), and we assume the reader to be have the education in commutative algebra and homological algebra that these chapters imply.^[See the Introduction of EGA I for more precise details.]
Furthermore, in each volume of the *Séminaire*, we will freely refer, as needed, to previous volumes of the same *Séminaire*, or to other chapters of "*Éléments*", either already published or on the brink of being published.

Each *volume* of the *Séminaire* is based on a main subject, indicated in the title of the corresponding volume(s);
the oral seminar generally lasts one academic year, sometimes more.
The exposés within each volume of the *Séminaire* are generally in a logical order of dependence on one another;
however, the different volumes of the *Séminaire* are largely logically independent of one another.
\oldpage{x}
So the volume "Group schemes" is largely logically independent of the two volumes of the *Séminaire* that come before it chronologically;
however, it makes frequent reference to results of EGA IV.
Here is the list of the volumes of the *Séminaire* that should appear (cited as SGA I to SGA 7 in what follows):

- SGA 1. Étale covers and the fundamental group, 1960/61.
- SGA 2. Local cohomology of coherent sheaves and local and global Lefschetz theorems, 1961/62.
- SGA 3. Group schemes, 1963/64 (3 volumes, in collaboration with M. Demazure).
- SGA 4. Topos theory and étale cohomology of schemes, 1963/64 (3 volumes, in collaboration with M. Artin and J.L. Verdier).
- SGA 5. $\ell$-adic cohomology and $L$-functions, 1964/65 (2 volumes).
- SGA 6. Intersection theory and the Riemann--Roch theorem, 1966/67 (2 volumes, in collaboration with P. Berthelot and L. Illusie).
- SGA 7. Local monodromy groups in algebraic geometry.

Three of these partial *Séminaires* have been written in *collaboration* with other mathematicians, who appear as coauthors on the covers of the corresponding volumes.
As for the other active participants of the *Séminaire*, whose roles (from as much of an editorial point of view as a mathematical one) have grown over the years, the name of each participant appears at the top of the exposés for which they are responsible, either as speaker or as writer, and the list of those who appear in a given volume can be found on the flyleaf of the volume in question.


It is useful to give some precise remarks concerning the relation between the *Séminaire* and the *Éléments*.
The latter was intended, in principle, to give an exposé of a set of ideas and techniques that were judged to be the most fundamental in Algebraic Geometry, as these ideas and techniques emerge all by themselves from the natural requirements of logical and aesthetic coherence.
From this point of view, it was natural to consider the *Séminaire* as a preliminary version of the *Éléments*, destined to be included almost entirely, sooner or later, in the latter.
This process had already somewhat started a few years ago, since exposés [I](#I) to [IV](#IV) of the current volume (SGA 1) are entirely covered by EGA IV, and exposés [VI](#VI) to [VIII](#VIII) should be, in some years, in EGA VI.
However, given how the work in constructing the *Éléments* and the *Séminaire* is developing, and as the proportions of the two become more precise, the initial principle (that the *Séminaire* should be only a preliminary and provisional version) seems less and less realistic, for the reason (amongst others) of the limits imposed by the long-sighted nature of the length of the human life.
Taking into account the care that is generally given to the writing of the various parts of the *Séminaire*, there will doubtless be no need to go back over them in the Éléments (or other treaties that would take over from it) until further progress in the writing process would allow us to make very substantial improvements, at the cost of rather big changes.
\oldpage{xi}
This is the case as of now for the current seminar SGA 1, as we said above, and also for SGA 2 (thanks to recent results by Mme. Raynaud).
However, nothing currently indicates that this will also be the case in the near future for any of the other parts mentioned above (SGA 3 to SGA 7).

The references in the "*Séminaire de Géométrie Algébrique du Bois-Marie*" are in the following format.
An *interior reference* to one of the parts SGA 1 to SGA 7 of the *Séminaire* is given in the form [III 9.7](#III.9.7), where the "III" denotes the number of the exposé, which appears at the top of each page of the exposé in question, and "9.7" is the number of the statement (or definition, remark, etc.) inside this exposé.
If necessary, longer decimal numbers may be used, e.g. [9.7.1](#III.9.7.1) and [9.7.2](#III.9.7.2), to denote the various steps in the proof of [Proposition 9.7](#III.9.7).
The reference [III 9](#III.9) denotes section 9 of exposé III.
The number of the exposé is omitted for references internal to an exposé.
For a *reference to another* of the *parts* of the *Séminaire*, we use the same notation, but preceded by the mention of the part of the SGA in question, e.g. [SGA 1 III 9.7](#III.7).
Similarly, the reference EGA IV 11.5.7 means: Éléments de Géométrie Algébrique, Chapter IV, statement (or definition, etc.) 11.5.7;
here, the first arabic numeral denotes again the number of the section.
As well as these conventions used throughout the SGA, the bibliography for an exposé will generally be printed at the end of the exposé in question, and references to it inside the exposé will be in the form of numbers between brackets, such as [@3].

Finally, for the ease of the reader, every time that it seems necessary, at the end of the volumes of the SGA we attach an index of notation and an index of terminology containing, if necessary, an English translation of the French terms used.

I want to add an extra-mathematical comment to this introduction.
In the month of November, 1969, I discovered that the Institut des Hautes Études Scientifiques, where I have been a professor essentially since its founding, had been receiving subventions from the Ministère des Armées for three years.
Already as a young researcher, I found it extremely regrettable how few qualms the majority of scientist had in agreeing to collaborate in one form or another with military institutions.
My motivations back then were essentially of a moral nature, and thus not very likely to be taken seriously.
Today they acquire a new force and dimension, given the danger of destruction of the human species threatened by the proliferation of military institutions and of the means of mass destruction that they posses.
I have explained my thoughts on these problems, which are much more important than the advancement of any of the sciences (mathematics included), in more detail in other places;
the reader can, for example, consult the article by G. Edwards in the Volume 1 of the journal *Survivre* (August, 1970), which gives a more detailed summary of these problems than I have done elsewhere.
\oldpage{xii}
So I found myself working for three years at an institution even though it was, unbeknownst to me, participating in a finance model that I consider immoral and dangerous.^[It goes without saying that the opinion that I express here is entirely my own, and not that of the publishing house Springer, which is editing this volume.]
Being currently the only person to have this opinion amongst my colleagues at the IHES, which has condemned my efforts to suppress military subventions from the IHES budget to fail, I have taken the necessary decision to leave the IHES on the 30th of September, 1970, and to equally suspend all scientific collaboration with this institute, for as long as it continues to accept such subventions.
I have asked M. Motchane, the director of the IHES, for the IHES to abstain, starting from the 1st of October, 1970, from sharing mathematical texts of which I am an author, or which form part of the *Séminaire de Géométrie Algébrique du Bois Marie*.
As was mentioned above, the diffusion of this seminar will be undertaken by the publishing house Julius Springer, in the *Lecture Notes* series.
I am happy to thank here Springer and Mr. K. Peters for the efficient and polite help that they have given me in making this publication possible, in particular for dealing with the typing of the photo-offset of new exposés added to old seminars, and of exposés missing incomplete seminars.

I equally thank Mr. J.P. Delale, who had the thankless job of compiling the index of notation and the index of terminology.

*Massy, August 1970.*


# Foreword {#foreword}

\oldpage{xiii}
Each of these written exposés covers the material of multiple consecutive oral exposés.
It did not seem useful to make a note of the dates.

Exposé VII, which is referenced at various points throughout [Exposé VIII](#VIII), has not been written by the speaker, who, in the oral conferences, was limited to outlining the language of descent in general categories, by working from a strictly utilitarian point of view and not entering into the logical difficulties that often arise due to this language.
It seemed that a proper exposé of this language would go beyond the limits of these current notes, even if only due to length.
For a proper exposé of the theory of descent, I refer the reader to an article in preparation by Jean Giraud.
Whilst waiting for its appearance^[It is now published: J. Giraud, "Méthode de la Descente". *Bull. Soc. Math. France* **2** (1964), viii + 150 p.], I think that an attentive reader will have no problems in supplementing, by their own means, the phantom references in [Exposé VIII](#VIII).

Other oral exposés, found after [Exposé XI](#XI), and to which there are references in certain places of the text, have also not been written down, and were meant to form the substance of an Exposé XII and an Exposé XIII.
The first of these oral exposés covered, in the framework of schemes and analytic spaces with nilpotent elements (as introduced in the *Séminaire Cartan 1960/61*), the construction of the analytic space associated to a prescheme of locally finite type over a complete valuation field $k$, GAGA-type theorems in the case where $k$ is the field of complex numbers, and the application to the comparison of the fundamental group defined by transcendental methods and the fundamental group studied in these notes (cf. A. Grothendieck, "Fondements de la Géométrie Algébrique". *Séminaire Bourbaki* **190** (December 1959), page 10).
The latter oral exposés outlined the generalised of methods developed in the text for the study of coverings that admit moderate ramification, and of the structure of the fundamental group of a complete curve minus a finite number of points (cf. *loc. cit.* **182**, page 27, théorème 14).
\oldpage{xiv}
These exposés do not introduce any essentially new ideas, which is why it did not seem necessary to write them up properly before the appearance of the corresponding chapters of *Éléments de Géométrie Algébrique*.^[They are included in the present volume in [Exposé XII](#XII) by Mme Raynaud with a different proof from the original given in the oral seminar (cf. [Introduction](#introduction)).]

However, the Lefschetz type theorems for the fundamental group and the Picard group, from both a local and a global point of view, were the subject of a separate seminar in 1962, which was completely written down and is available to read.^[*Cohomologie étale des faisceaux cohérents et théorèmes de Lefschetz locaux et globaux* (SGA 2), appeared in North Holland Pub. Cie.]
We point out that the results developed, both in the present *Séminaire* and the seminar from 1962, will be used in an essential manner in the appearance of many key results about the étale cohomology of preschemes, which will be the subject of a *Séminaire* (led by M. Artin and myself) in 1963/64, currently in preparation.^[*Cohomologie étale des schémas* (SGA 4), to appear in the same series.]
Exposés [I](#I) to [IV](#IV), which are of an essentially local nature, and very elementary, will be absorbed entirely by chapter IV of *Éléments de Géométrie Algébrique*, of which the first part is being printed and will probably be published towards the end of 1964.
They can, nevertheless, be useful for a reader who wants to catch up to speed with the essential properties of smooth, étale, or flat morphisms, before diving into the arcana of a systematic treatment.
As for the other exposés, they will be absorbed into chapter VIII^[In fact, following a change to the initial plan for the *Éléments*, the study of the fundamental group has been postponed to a later chapter of the *Éléments*, cf. the [Introduction](#introduction) that precedes this foreword.] of the *Éléments*, whose publication can barely even be contemplated for many years.

*Bures, June 1963.*
