## 11. Various addenda {#I.11}

We have already said that a connected étale cover of an integral scheme is not necessarily integral.
Here are two examples of this fact.

a. Let $C$ be an algebraic curve with an ordinary double point $x$, and let $C'$ be its normalisation, with $a$ and $b$ the two points of $C'$ over $x$.
  Let $C'_1$ and $C'_2$ be copies of $C'$, with $a_i$ (resp. $b_i$) the point of $C'_i$ corresponding to $a$ (resp. $b$).
  In the curve $C'_1\coprod C'_2$, we identify $a_1$ with $b_2$, and $a_2$ with $b_1$ (we leave making this process of identification precise to the reader; it will be explained in Chapter VI of the multiplodoque, but, in the case of curves over an algebraically closed field, is already covered in Serre's book on algebraic curves).
  We obtain a curve $C''$ which is _connected_ and _reducible_, and which is a degree-$2$ étale cover of $C$.
  The reader can verify that, generally, the "Galois" connected étale covers $C''$ of $C$ whose inverse images $C''\times_C C'$ are _trivial_ covers of $C'$ (i.e. isomorphic to the sum of a certain number of copies of $C'$) are "cyclic" of degree $n$, and, conversely, for every integer $n>0$, we can construct a cyclic connected étale cover of degree $n$.
  In the language of the fundamental group (which will be developed later), this implies that the quotient of $\pi_1(C)$ by the closed invariant subgroup generated by the image of $\pi_1(C')\to\pi_1(C)$ (the homomorphism induced by the projection) is isomorphic to the compactification of $\mathbb{Z}$.
  More precisely, we should show that the fundamental group of $C$ is isomorphic to the (topological) free product of the fundamental group of $C$ with the compactification of $\mathbb{Z}$.
  We note that is was questions of this sort that gave birth to the "theory of descent" for schemes.

b. Let $A$ be a complete integral local ring;
  we know that its normalisation $A'$ is finite over $A$ (by Nagata), and is thus a complete semi-local ring, and thus local, since it is integral.
  Suppose that the residue extension $L/k$ that it defines is non-radicial (in the contrary case, we say that $A$ is _geometrically unibranch_; cf. below).
  This will be the case, for example, for the ring $\mathbb{R}[[s,t]]/(s^2+t^2)\mathbb{R}[[s,t]]$, where $\mathbb{R}$ is the field of real numbers.
  Then let $k'$ be a finite Galois extension of $k$ such that $L\otimes_k k'$ decomposes;
  let $B$ be a finite and étale algebra over $A$ corresponding to the residue extension $k'$ (recall that $B$ is essentially unique).
  Then the residue algebra of $B'=A'\otimes_A B$ over $B$ is $L\otimes_k k'$, which is not local, and so $B'$ is not a local ring, and thus $B$ has zero divisors (since it is complete).
  Now $B'$ is contained in the total ring of fractions of $B$ (since it is free over $A'$, thus torsion free over $A'$, thus torsion free over $A$, thus contained in $B'\otimes_A K=B'_{(K)}=A'_{(K)}\otimes_K B_{(K)}=B_{(K)}$, since $A'_{(k)}=K$), and so $B$ is not integral.
  In the case of the ring $\mathbb{R}[s,t]/(s^2+t^2)\mathbb{R}[s,t]$, taking $k'/k=\mathbb{C}/\mathbb{R}$, we see that $B$ is the local ring of two secant lines at their point of intersection.

  We note also that, if there exists a connected étale cover $X$ of $Y$ that is integral but not irreducible, then every irreducible component of $X$ gives an example of an unramified cover $X'$ of $Y$ that dominates $Y$ but is not étale over $Y$.
  In the case of example (a), we thus see that $C'$ is unramified over $C$, without being étale at the two points $a$ and $b$ (note that, directly, by inspection of the completions of the local rings at $x$ and $a$, from the "formal" point of view, $C'$ at the point $a$ can be identified with a closed subscheme of $C$ at the point $x$, i.e. one of the two "branches" of $C$ passing through $x$).

In both (a) and (b), we see that the fact that the conclusions of [9.5 (i) and (ii)](#I.9.5) fail to hold is directly linked with the fact that a point of $Y$ "blows up" at _distinct_ points of the normalisation (in (b), the fact that the residue extension is non-radicial should be interpreted geometrically in this way).
More precisely, we say that an integral local ring $A$ is _geometrically unibranch_ if its normalisation has only a single maximal ideal, with the corresponding residue extension being radicial;
a point $y$ of an integral prescheme is said to be geometrically unibranch if its local ring is geometrically unibranch.
_Examples:_
a normal point, an ordinary cusp point of a curve, etc.
It seems that, if $Y$ admits a point which is not unibranch, then there always exists a non-irreducible connected étale cover of $Y$;
at least, this is what we have shown in case (b), when $Y$ is the spectrum of a complete local ring.
We can show, however, that _if all the points of $Y$ are geometrically unibranch, then every unramified connected $Y$-prescheme that dominates $Y$ is étale and irreducible_.
The proof follows that of [9.5](#I.9.5), using the following generalisation of [Theorem 8.3](#I.8.3), which will be proved later by means of the technique of descent:^[cf. [IX 4.10](#IX.4.10). For a more direct demonstration, cf. EGA IV 18.10.3, using a variant of [9.5](#I.9.5) for geometrically unibranch local rings.]
