## 2. Some smoothness criteria for morphisms {#II.2}

::: {.itenv #II.2.1 title="Theorem 2.1" latex="{Theorem 2.1}"}
Let $f\colon X\to Y$ be a morphism locally of finite type, and let $x\in X$ and $y=f(x)$.
For $f$ to be smooth at $x$, it is necessary and sufficient that

a. $f$ be flat at $x$, and
b. $f^{-1}(y)$ be smooth over $k(y)$ at $x$.
:::

::: {.proof}
Since the composite of two flat morphisms is flat, and since $Y[t_1,\ldots,t_n]\to Y$ is a flat morphism, we see that smooth implies flat;
taking [1.3, (ii)](#II.1.3) into account, this proves necessity.
Now suppose that (a) and (b) are satisfied, and let $V$ be an affine neighbourhood of $y$ of ring $A$, and $U$ an affine neighbourhood of $x$ over $V$ of ring $B$.
Taking $U$ to be small enough, we can suppose, by (b), that there exists an *étale* $k(y)$-morphism
$$
  g\colon U|f^{-1}(y)
  \to \Spec k[t_1,\ldots,t_n]
  \qquad\text{(where }k=k(y)\text{)}
$$
defined by $n$ sections $g_i$ of the structure sheaf of $U|f^{-1}(y)$.
We easily note that we can suppose the $g_i$ (which are a priori elements of $B\otimes_A k=BS^{-1}$, where $S=A\setminus\frak{p}$, with $\frak{p}$ the prime ideal of $A$ corresponding to $y$) to come from sections of the structure sheaf of $U$, so that $g$ is induced by a morphism, also denoted by $g$,
$$
  g\colon U
  \to Y[t_1,\ldots,t_n]
$$
(after possibly multiplying the $g_i$ by a single non-zero element of $k$).
But $U$ is flat over $Y$ by (a), and so too is $Y[t_1,\ldots,t_n]$;
we also know that $g$ induces an étale morphism between the fibres over $y$, and so $g$ is étale at $x$ by [I 5.8](#I.5.8).
:::

::: {.itenv #II.2.2 title="Corollary 2.2" latex="{Corollary 2.2}"}
Let $S$ be a prescheme, and let $f\colon X\to Y$ an $S$-morphism of finite type, with $Y$ of finite type and flat over $S$.
Let $x\in X$, and let $s$ be the projection of $x$ to $S$.
For $f$ to be smooth at $x$, it is necessary and sufficient that $X$ be flat (or smooth) over $S$ at $x$, and that the induced morphism $f_s\colon X_s\to Y_s$ between the fibres over $s$ be smooth at $x$.
:::

::: {.proof}
Only the sufficiency needs proving, and this follows from [2.1](#II.2.1), combined with the flatness criterion [I 5.9](#I.5.9).
:::

To state the following result, "recall" that a morphism $f\colon X\to Y$ locally of finite type is said to be *equidimensional* at the point $x\in X$ if (setting $y=f(x)$) we can find an open neighbourhood $U$ of $x$ of which every component dominates a component of $Y$ such that, for all $y'\in Y$, the irreducible components of $f^{-1}(y')\cap U$ all have the same dimension, independent of $y$.
It suffices, in this condition, to take $y'$ to be the generic points of the irreducible components of $Y$ passing through $y$, *and* the point $y$ itself.
If, for example, $X$ and $Y$ are integral and $f$ is dominant, then the condition implies that the components of the $f^{-1}(y)$ passing through $x$ have "the good" dimension, i.e. the dimension of the generic fibre (recall that they are always $\geq$ the dimension of the generic fibre).
If $f$ is equidimensional at $x$, with the dimension of its fibre at $x$ being $n$, and if $g\colon U\to Y'=Y[t_1,\ldots,t_n]$ is a $Y$-morphism on a neighbourhood $U$ of $x$ that induces a morphism on the fibres of $y$ that is quasi-finite at $x$ (or, equivalently, if $g$ is quasi-finite at $x$), then we can show that every irreducible component of $U$ passing through $x$ dominates an irreducible component of $Y'$.
By the "normalisation lemma", such a $g$ always exists (and, conversely, if there exists a quasi-finite $Y$-morphism $g$ on an open neighbourhood $U$ of $x$ into a $Y$-scheme of the form $Y'=Y[t_1,\ldots,t_n]$ such that every component of $U$ passing through $x$ dominates a component of $Y'$, then $f$ is equidimensional at $x$).
Then:

::: {.itenv #II.2.3 title="Proposition 2.3" latex="{Proposition 2.3}"}
Let $f\colon X\to Y$ be a morphism locally of finite type, and let $x\in X$, and $y=f(x)$.
Suppose that $\cal{O}_y$ is normal.
For $f$ to be smooth at $x$, it is necessary and sufficient that $f$ be equidimensional at $x$, and that $f^{-1}(y)$ be smooth over $k(y)$ at $x$.
:::

::: {.proof}
We immediately see from the definition that a smooth morphism is equidimensional (N.B. a flat morphism of finite type is not necessary equidimensional at $x$, even if its fibre at $x$ is irreducible).
Let us prove the converse.
Since $f^{-1}(y)$ is smooth over $k(y)$ at $x$, we can suppose (by replacing, if necessary, $X$ by a suitable neighbourhood of $x$) that there exists a $Y$-morphism
$$
  g\colon X\to Y[t_1,\ldots,t_n] = Y'
$$
that induces an étale morphism on the fibres of $y$, and is a fortiori quasi-finite at $x$.
Thus $g$ is unramified, and (since $f$ is equidimensional at $x$) the irreducible components of $X$ that contain $x$ each dominate a component of $Y'$, and a fortiori the homomorphism $\cal{O}_{y'}\to\cal{O}_x$ induced by $g$ (where $y'=g(x)$) is *injective*.
This homomorphism is also unramified, and $\cal{O}_{y'}$ is normal since it is the localisation of the ring $\cal{O}_y[t_1,\ldots,t_n]$, which is itself normal since $\cal{O}_y$ is.
Thus the homomorphism $\cal{O}_{y'}\to\cal{O}_x$ is étale [I 9.5 (ii)](#I.9.5).
:::

::: {.rmenv #II.2.4 title="Remarks 2.4" latex="{Remarks 2.4}"}
The previous statement still holds if we replace the hypothesis that $\cal{O}_y$ is normal with the weaker hypothesis that $Y$ is *geometrically unibranch* at $y$ (cf. [I 11](#I.11)) --- since [I 9.5](#I.9.5) still holds under this hypothesis.
We also point out at the same time that if the residue field of an integral local ring $A$ is algebraically closed, and thus algebraically integral (i.e. $\hat{A}$ is integral), then it is also geometrically unibranch;
the converse is true as well in any category of "good rings", or, more precisely, in any category of rings that is stable under the usual operations, and where the completion of a normal local ring is normal (a conditions which is satisfied, by Zariski's "analytic normality theorem", in the category of affine algebras and their localisations).^[cf. EGA IV 7.8.]

Finally, "recall" in the current context the following result, due to Hironaka^[cf. EGA IV 5.12.10.], which sometimes allows us to assume that $f^{-1}(y)$ is a reduced scheme, i.e. that it is also what many algebraic geometers consider (as an abuse) as the fibre (without multiplicity) of $f$ over $x$ (i.e. $f^{-1}(y)_\mathrm{red}$):
:::

::: {.itenv #II.2.5 title="Proposition 2.5" latex="{Proposition 2.5}"}
Let $f\colon X\to Y$ be a dominant morphism of finite type between reduced preschemes, and $y$ be a point of $Y$ such that $\cal{O}_y$ is regular.
Suppose that all the components of $f^{-1}(y)$ are of multiplicity $1$ (cf. the definition below), and that $f^{-1}(y)_\mathrm{red}$ is normal.
Then $f^{-1}(y)$ is reduced and thus normal, $X$ is normal at every point of $f^{-1}(y)$, and finally $X$ is flat over $Y$ at every point of $f^{-1}(y)$.
:::

We say that a component $Z$ of $f^{-1}(y)$ is of *multiplicity* $1$ if, denoting by $x$ the generic point of $Z$, we have

i. $\dim\cal{O}_x=\dim\cal{O}_y$ (i.e. $Z$ is not an "excess component", i.e. it is not "of too large dimension")
ii. the maximal ideal of $\cal{O}_x$ is generated by the maximal ideal of $\cal{O}_y$ (which, a priori, by the choice of $x$, generates an ideal of definition of $\cal{O}_x$).

Taking [2.3](#II.2.3) or [2.1](#II.2.1) into account, we thus find:

::: {.itenv #II.2.5 title="Corollary 2.6" latex="{Corollary 2.6}"}
Let $f\colon X\to Y$ be a dominant morphism of finite type between reduced preschemes, and $y$ a point of $Y$ such that $\cal{O}_y$ is regular.
For $f$ to be smooth at all the points of $X$ over $y$, it is necessary and sufficient that the components of $f^{-1}(y)$ be of multiplicity $1$ and that $f^{-1}(y)_\mathrm{red}$ be smooth over $k(y)$.
:::

In the past, this situation was mostly considered with $Y$ being the spectrum of a discrete valuation ring $A$, and was generally described with phrases such as "if the reduction of $X$ with respect to the given valuation is good...".
Furthermore, $X$ then denoted a closed subscheme (if we can say that) of some $\mathbb{P}_K^n$ (with $K$ the field of fractions of $A$), and, due to a lack of adequate language, the more intrinsic role of an object "defined over $A$" (and not only over $K$) didn't really appear.
