## 7. Local construction of unramified and étale morphisms {#I.7}

\oldpage{10}

::: {.itenv #I.7.1 title="Proposition 7.1"}
Let $A$ be a Noetherian ring, $B$ an algebra which is finite over $A$, and $u$ a generator of $B$ over $A$.
Let $F\in A[t]$ be such that $F(u)=0$ (we do not assume $F$ to be monic), and $u'=F'(u)$ (where $F'$ is the differentiated polynomial).
Let $\frak{q}$ be a prime ideal of $B$ not containing $u'$, and $\frak{p}$ its intersection with $A$.
Then $B_\frak{q}$ is unramified over $A_\frak{p}$.
:::

In other words, taking $Y=\Spec(A)$, $X=\Spec(B)$, and $X_{u'}=\Spec(B_{u'})$, we claim that $X_{u'}$ is unramified over $Y$.
This statement follows from the following, more precise:

::: {.itenv #I.7.2 title="Corollary 7.2"}
The different ideal of $B/A$ contains $u'B$, and is equal to $u'B$ if the natural homomorphism $A[t]/FA[t]\to B$ (sending $t$ to $u$) is an isomorphism.
}
:::

::: {.proof}
Let $J$ be the kernel of the homomorphism $C=A[t]\to B$, so that $J$ contains $FA[t]$, and is equal to it in the second case described in [7.2](#I.7.2).
Since the homomorphism $C\to B$ is surjective, $\Omega_{B/A}^1$ can be identified with the quotient of $\Omega_{C/A}^1$ by the sub-module generated by $J\Omega_{C/A}^1$ and $\dd(J)$ (we should have explicitly described the definition of the homomorphism $d$ and the calculation of $\Omega^1$ for an algebra of polynomials in [§1](#I.1)).
Identifying $\Omega_{C/A}^1$ with $C$, via the basis $\dd t$, we obtain $B/B\cdot J'$, and so the different ideal is generated by the set $J'$ of images in $B$ of derivatives of $G\in J$ (and it suffices to take $G$ that generate $J$).
Since $F\in J$ (resp. $F$ is a generator of $J$), we are done.
:::

We thus find:

::: {.itenv #I.7.3 title="Corollary 7.3"}
Under the conditions of [7.1](#I.7.1), and supposing that $F$ is monic and that $A[t]/FA[t]\to B$ is an isomorphism, in order for $B_\frak{q}$ to be étale over $A_\frak{p}$, it is necessary and sufficient for $\frak{q}$ to not contain $u'$.
:::

::: {.proof}
Since $B$ is flat over $A$, being étale is equivalent to being unramified, and we can apply [7.2](#I.7.2).
:::

::: {.itenv #I.7.4 title="Corollary 7.4"}
Under the conditions of [7.3](#I.7.3), in order for $B$ to be étale over $A$, it is necessary and sufficient for $u'$ to be invertible, or for the ideal $F'$ generated by $F$ in $A[t]$ to be the unit ideal.
:::

::: {.proof}
The second claim follows from the first along with Nakayama (in $B$).
:::

\oldpage{11}

A monic polynomial $F\in A[t]$ that has the property stated in [7.4](#I.7.4) is said to be a _separable polynomial_ (if $F$ is not monic, we must at least require that the coefficient of its leading term be invertible; in the case where $A$ is a field, we recover the usual definition).

::: {.itenv #I.7.5 title="Corollary 7.5"}
Let $B$ be an algebra which is _finite_ over the _local_ ring $A$.
Suppose that $K(A)$ is infinite, or that $B$ is local.
Let $n$ be the rank of $L=B\otimes_A K(A)$ over $K(A)=k$.
For $B$ to be unramified (resp. étale) over $A$, it is necessary and sufficient for $B$ to be isomorphic to a quotient of (resp. isomorphic to) $A[t]/FA[t]$, where $F$ is a separable monic polynomial, which we can assume to be (resp. which is necessarily of) degree $n$.
:::

::: {.proof}
We only have to prove necessity.
Suppose that $B$ is unramified over $A$, and thus that $L$ is separable over $k$.
It then follows from the hypotheses that $L/k$ admits a generator $\xi$, and thus the $\xi^i$ (for $0\leq i<n$) form a basis for $L$ over $k$.
Let $u\in B$ be a lift of $\xi$;
by Nakayama, the $u^i$ (for $0\leq i<n$) generate (resp. form a basis of) the $A$-module $B$, and, in particular, we obtain a monic polynomial $F\in A[t]$ such that $F(u)=0$;
$B$ is then isomorphic to a quotient of (resp. isomorphic to) $A[t]/FA[t]$.
Finally, by applying [7.4](#I.7.4) to $L/k$, we see that $F$ and $F'$ generate $A[t]$ modulo $\frak{m}A[t]$, and so (by Nakayama in $A[t]/FA[t]$) $F$ and $F'$ generate $A[t]$, and we are done.
:::

::: {.itenv #I.7.6 title="Theorem 7.6"}
Let $A$ be a local ring, and $A\to\cal{O}$ a local homomorphism such that $\cal{O}$ is isomorphic to the localisation of an algebra of finite type over $A$.
Suppose that $\cal{O}$ is _unramified_ over $A$.
Then we can find an $A$-algebra $B$ which is integral over $A$, a maximal ideal $\frak{n}$ of $B$, a generator $u$ of $B$ over $A$, and a monic polynomial $F\in A[t]$ such that $\frak{n}\not\ni F'(u)$ and such that $\cal{O}$ is isomorphic (as an $A$-algebra) to $B_\frak{n}$.
If $\cal{O}$ is étale over $A$, then we can take $B=A[t]/FA[t]$.
:::

(Of course, these conditions are more than sufficient ...)

Before proving [7.6](#I.7.6), we first state some nice corollaries:

::: {.itenv #I.7.7 title="Corollary 7.7"}
For $\cal{O}$ to be unramified over $A$, it is necessary and sufficient for $\cal{O}$ to be isomorphic to the quotient of an algebra which is unramified and _étale_ over $A$.
:::

::: {.proof}
We can take $\cal{O}'=B'_{\frak{n}'}$, where $B'=A[t]/FA[t]$ and where $\frak{n}'$ is the inverse image of $\frak{n}$ in $B'$.
:::

\oldpage{12}

::: {.itenv #I.7.8 title="Corollary 7.8"}
Let $f\colon X\to Y$ be a morphism of finite type, and $x\in X$.
For $f$ to be unramified at $x$, it is necessary and sufficient for there to exist an open neighbourhood $U$ of $x$ such that $f|U$ factors as $U\to X'\to Y$, where the first arrow is a closed immersion, and the second is an étale morphism.
:::

::: {.proof}
This is a simple translation of [7.7](#I.7.7).
:::

We will now show how the jargon of [7.6](#I.7.6) follows from the main theorem:
there exists, by [7.7](#I.7.7), an epimorphism $\cal{O}'\to\cal{O}$, where $\cal{O}$ has all the desired properties;
but since $\cal{O}'$ and $\cal{O}$ are étale over $A$, the morphism $\cal{O}'\to\cal{O}$ is étale by [4.8](#I.4.8), and thus an isomorphism.

::: {.proof name="of Theorem 7.6"}
This repeats a proof from the _Séminaire Chevalley_.
By the "Main Theorem", we have that $\cal{O}=B_\frak{n}$, where $B$ is an algebra which is finite over $A$, and $\frak{n}$ is a maximal ideal.
Then $B/\frak{n}=B(\cal{O})$ is a separable, and thus monogenous, extension of $k$;
if $\frak{n}_i$ (for $1\leq i\leq r$) are maximal ideas of $B$ that are distinct from $\frak{n}$, then there thus exists an element $u$ of $B$ that belongs to all the $\frak{n}_i$, and thus whose image in $B/\frak{n}$ is a generator.
But $B/\frak{n}=B_\frak{n}/\frak{n}B_\frak{n}=B_\frak{n}/\frak{m}B_\frak{n}$ (where $\frak{m}$ is the maximal ideal of $A$).

Suppose, for the moment, that we have both [7.9](#I.7.9) and [7.10](#I.7.10).
Let $n$ be the rank of the $k$-algebra $L=B\otimes_A k$.
By Nakayama, there exists a monic polynomial of degree $n$ in $A[t]$ such that $F(u)=0$.
Let $f$ be the polynomial induced from $F$ by reduction $\mod\frak{m}$.
Then $L$ is $k$-isomorphic to $k[t]/fk[t]$, and so, by [7.3](#I.7.3), $f'(\xi)$ is not contained in the maximal ideal of $L$ that corresponds to $\frak{n}$ (where $\xi$ denotes the image of $t$ in $L$, i.e. the image of $u$ in $L$).
Since $f'(\xi)$ is the image of $F'(u)$, we are done.
:::

::: {.itenv #I.7.9 title="Lemma 7.9"}
Let $A$ be a local ring, $B$ an algebra which is finite over $A$, $\frak{n}$ a maximal ideal of $B$, and $u$ an element of $B$ whose image in $B_\frak{n}/\frak{m}B_\frak{n}$ is a generator as an algebra over $k=A/\frak{m}$, and such that $u$ is contained in every maximal ideal of $B$ that is distinct from $\frak{n}$.
Let $B'=B[u]$ and $\frak{n}'=\frak{n}B'$.
Then the canonical homomorphism $B'_{\frak{n}'}\to B_\frak{n}$ is an isomorphism.
:::

::: {.itenv #I.7.10 title="Lemma 7.10"}
Let $B$ be a algebra which is finite over $A$ and generated by a single element $u$, and let $\frak{n}$ be a maximal ideal of $B$ such that $B_\frak{n}$ is unramified over $A$.
Then there exists a monic polynomial $F\in A[t]$ such that $F(u)=0$ and $F'(u)\not\in\frak{n}$.
:::

N.B. [7.10](#I.7.10) should have appeared as a corollary to [7.1](#I.7.1), and before [7.5](#I.7.5) (which it implies).

\oldpage{13}

So [7.6](#I.7.6) now follows from the combination of [7.9](#I.7.9) and [7.10](#I.7.10);
it remains only to prove [7.9](#I.7.9).

::: {.proof name="of Lemma 7.9"}
Let $S'=B'\setminus\frak{n}'$, so that $B'S'^{-1}=B'_\frak{n'}$.
Similarly, let $S=B\setminus\frak{n}$, so that $BS^{-1}=B_\frak{n}$.
We then have a natural homomorphism $BS'^{-1}\to BS^{-1}=B_\frak{n}$;
we will show that this is an isomorphism, i.e. that the elements of $S$ are invertible in $BS'^{-1}$, i.e. that every maximal ideal $\frak{p}$ of $BS'^{-1}$ does not meet $S$, i.e. that every maximal ideal of $BS'^{-1}$ induces $\frak{n}$ on $B$.
$$
  \begin{CD}
    B @>>> BS'^{-1} @>>> BS^{-1} = B_\frak{n}
  \\@AAA @AAA
  \\B' @>>> B'S'^{-1} = B'_{\frak{n}'}
  \end{CD}
$$
Since $BS'^{-1}$ is finite over $B'S'^{-1}=B'_{\frak{n}'}$, $\frak{p}$ induces the unique maximal ideal $\frak{n}'B_{\frak{n}'}$ of $B'_{\frak{n}'}$, and thus induces the maximal ideal $\frak{n}'$ of $B'$;
since $B$ is finite over $B'$, the ideal $\frak{q}$ of $B$ induced by $\frak{p}$, which lives over $\frak{n}'$, is necessarily maximal, and does not contain $u$, and is thus identical to $\frak{n}$.
(We have just used the fact that $u$ belongs to every maximal ideal of $B$ that is distinct from $\frak{n}$).
We now prove that $BS'^{-1}$ is equal to $B'S'^{-1}$:
since the former is finite over the latter, we can reduce, by Nakayama, to proving equality modulo $\frak{n}'BS'^{-1}$, and, a fortiori, it suffices to prove equality modulo $\frak{m}BS'^{-1}$;
but $BS'^{-1}/\frak{m}BS'^{-1}=B_\frak{n}/\frak{m}B_\frak{n}$ is generated, over $k$, by $u$ (here we use the other property of $u$), and so the image of $B'$ (and, a fortiori, of $B'S'^{-1}$) inside is everything (as a subring that contains $k$ and the image of $u$.)
:::

::: {.rmenv title="Remark"}
We must be able to state [7.6](#I.7.6) for a ring $\cal{O}$ which is only semi-local, so that we also cover [7.5](#I.7.5):
we make the hypothesis that $\cal{O}/\frak{m}\cal{O}$ is a _monogenous_ $k$-algebra;
we can thus find some $u\in B$ whose image in $B/\frak{m}B$ is a generator, and belongs to every maximal ideal of $B$ that doesn't come from $\cal{O}$.
Both [7.9](#I.7.9) and [7.10](#I.7.10) should be able to be adapted without difficulty.
More generally, ...
:::
