## 6. Application to étale extensions of complete local rings {#I.6}

This section is a particular case of the results on formal preschemes, which should appear in the multiplodoque.
Nevertheless, here we get away without much difficulty, i.e. without the explicit local determination of the étale morphisms in [§7](I.7) (using the Main Theorem).
This is perhaps sufficient reason to keep this current section (even in the multiplodoque) where it is.

::: {.theorem #I.6.1}
  Let $A$ be a complete local ring (Noetherian, of course), with residue field $k$.
  For any $A$-algebra $B$, let $R(B)=B\otimes_Ak$ be thought of as a $k$-algebra;
  this depends functorially on $B$.
  Then $R$ defines an _equivalence_ between the category of $A$-algebras that are _finite and étale over $A$_ and the category of algebras that are _finite rank and separable over $k$_.
:::

Firstly, the functor in question is fully faithful, as follows from the more general fact:

::: {.corollary #I.6.2}
  Let $B$ and $B'$ be $A$-algebras that are finite over $A$.
  If $B$ is étale over $A$, then the canonical map
  \[
    \Hom_{\alg{A}}(B,B')
    \to \Hom_{\alg{k}}(R(B),R(B'))
  \]
  is bijective.
:::

::: {.proof}
  We can reduce to the case where $A$ is Artinian (by replacing $A$ by $A/\frak{m}^n$), and then it is a particular case of [5.5]{#I.5.5}.

  It remains to prove that, for every finite and separable $k$ algebra (or we can simply say "étale", for brevity) $L$, there exists some $B$ étale over $A$ such that $R(B)$ is isomorphic to $L$.
  We can suppose that $L$ is a separable extension of $k$, and, as such, it admits a generator $x$, i.e. it is isomorphic to an algebra $k[t]/Fk[t]$, where $F\in k[t]$ is a monic polynomial.
  We can lift $F$ to a monic polynomial $F_1$ in $A[t]$, and we take $B=A[t]/F_1A[t]$.
:::