## 9. Invariance properties {#I.9}

Let $A\to B$ be a local and étale morphism;
we study here some cases where a certain property of $A$ implies the same property for $B$, or vice versa.
A certain number of such propositions are already consequences of the simple fact that $B$ is _quasi-finite_ and _flat_ over $A$, and we content ourselves with "recalling" some of them:
_$A$ and $B$ have the same Krull dimension, and the same depth_ (Serre's "cohomological codimension", in the more modern language).
It also follows, for example, that _$A$ is Cohen--Macaulay if and only if $B$ is_.
Also, for any prime ideal $\frak{q}$ of $B$ (inducing some $\frak{p}$ of $A$), $B_\frak{q}$ is again quasi-finite and flat over $A_\frak{p}$, as long as we suppose that $B$ is the localisation of an algebra of finite type over $A$ (this follows from the fact that the set of points where a morphism of finite type is quasi-finite (resp. flat) is open);
further, _every_ prime ideal $\frak{p}$ of $A$ is induced by a prime ideal $\frak{q}$ of $B$ (since $B$ is _faithfully_ flat over $A$).
It thus follows, for example, that _$\frak{q}$ and $\frak{p}$ have the same rank_;
also, _$A$ has no embedded prime ideals if and only if $B$ has none_.

We will thus content ourselves with more specific propositions dealing with the case of étale morphisms.

::: {.itenv #I.9.1 title="Proposition 9.1"}
Let $A\to B$ be an étale local homomorphism.
For $A$ to be regular, it is necessary and sufficient for $B$ to be regular.
:::

::: {.proof}
Let $k$ be the residue field of $A$, and $L$ the residue field of $B$.
Since $B$ is flat over $A$, and since $L=B\otimes_A k$ (i.e. $\frak{n}=\frak{m}B$, where $\frak{m}$ and $\frak{n}$ are the maximal ideals of $A$ and $B$, respectively), the $\frak{m}$-adic filtration on $B$ is identical to the $\frak{n}$-adic filtration, and
$$
  \gr^\bullet(B) = \gr^\bullet(A)\otimes_k L.
$$
It follows that $\gr^\bullet(B)$ is a polynomial algebra over $L$ if and only if $\gr^\bullet(A)$ is a polynomial algebra over $K$.
(N.B. we have not used the fact that $L/k$ is separable.)
:::

::: {.itenv title="Corollary 9.2"}
Let $f\colon X\to Y$ be an étale morphism.
If $Y$ is regular, then $X$ is regular;
the converse is true if $f$ is surjective.
:::

::: {.itenv #I.9.2 title="Proposition 9.2"}
Let $f\colon X\to Y$ be an étale morphism.
If $Y$ is reduced, then $X$ is reduced;
the converse is true if $f$ is surjective.
:::

This is equivalent to the following:

::: {.itenv title="Corollary 9.3"}
Let $f\colon A\to B$ be an étale local homomorphism, with $B$ isomorphic to the localisation of an $A$-algebra of finite type over $A$.
For $A$ to be reduced, it is necessary and sufficient for $B$ to be reduced.
:::

::: {.proof}
The necessity is trivial, since $A\to B$ is injective (since $B$ is faithfully flat over $A$).
For the sufficiency, let $\frak{p}_i$ be the minimal prime ideals of $A$.
By hypothesis, the natural map $A\to\prod_i A/\frak{p}_i$ is injective, and so tensoring with the flat $A$-module $B$ gives that $B\to\prod_i B/\frak{p}_iB$ is injective, and we can thus reduce to proving that the $B/\frak{p}_iB$ are reduced.
Since $B/\frak{p}_iB$ is étale over $A/\frak{p}_i$, we can reduce to the case where $A$ is integral.
Let $K$ be the field of fractions of $A$, so that $A\to K$ is injective, and thus so too is $B\to B\otimes_A K$ (since $B$ is $A$-flat), and we can thus reduce to proving that $B\otimes_A K$ is reduced.
But $B$ is the localisation of an $A$-algebra of finite type over $A$, and thus is the local ring of a point $x$ of a scheme of finite type $X=\Spec(C)$ over $Y=\Spec(A)$ that is also _étale_ over $Y$, so $B\otimes_A K$ is a localised ring (with respect to some suitable multiplicatively stable set) of the ring $C\otimes_A K$ of $X\otimes_A K$.
Since $X\otimes_A K$ is étale over $K$, its ring is a finite product of fields (that are separable extensions of $K$), and thus so too is $B\otimes_A K$.
:::

::: {.itenv #I.9.4 title="Corollary 9.4"}
Let $f\colon A\to B$ be an étale local homomorphism, with $A$ analytically reduced (i.e. such that the completion $\hat{A}$ of $A$ has no nilpotent elements).
Then $B$ is analytically reduced, and a fortiori reduced.
:::

::: {.proof}
Indeed, $\hat{B}$ is _finite_ and étale over $\hat{A}$;
we can apply [9.3](#I.9.3).
:::

::: {.itenv #I.9.5 title="Theorem 9.5"}
Let $f\colon A\to B$ be a local homomorphism, with $B$ isomorphic to the localisation of an $A$-algebra of finite type over $A$.

i. If $f$ is étale, then $A$ is normal if and only if $B$ is normal.
ii. If $A$ is normal, then $f$ is étale if and only if $f$ is injective and unramified (and then $B$ is normal, by (i)).
:::

We will give two different proofs of (i):
the first using certain properties of quasi-finite flat morphisms (stated at the start of this section) and without using [7.6](#I.7.6) (and thus the Main Theorem);
the second proof does the opposite.
For (ii), it seems like we do indeed need the Main Theorem, no matter what.

:::: {.proof}
_(First proof)._
We use the following necessary and sufficient condition for a local Noetherian ring $A$ of dimension $\neq0$ to be normal.

::: {.itenv #serres-criterion title="Serre's criterion"}
—

i. For every rank-$1$ prime ideal $\frak{p}$ of $A$, $A_\frak{p}$ is normal (or, equivalently, regular);
ii. For every rank-$\geq2$ prime ideal $\frak{p}$ of $A$, the depth of $A_\frak{p}$ is $\geq2$.^[cf. EGA IV 5.8.6.]
:::

We assume this criterion here, but it should also appear in the section on flatness.
Its main advantage is that it does not suppose a priori that $A$ is reduced, nor a fortiori that $A$ is integral.
Here, we can already suppose that $\dim A=\dim B\neq0$.

By the statements at the start of this section, the rank-$1$ (resp. rank-$\geq2$) prime ideals $\frak{p}$ of $A$ are exactly the intersections of $A$ with the rank-$1$ (resp. rank-$\geq2$) prime ideals $\frak{q}$ of $B$.
Finally, if $\frak{p}$ and $\frak{q}$ correspond to one another, then $B_\frak{q}$ is étale over $A_\frak{p}$, and thus of the same depth as $A_\frak{p}$, and is regular if and only if $A_\frak{p}$ is (by [9.1](#I.9.1)).
Applying [Serre's criterion](#serres-criterion), we see that $A$ is normal if and only if $B$ is.
::::

::: {.proof}
_(Second proof)._
Suppose that $B$ is normal, with field of fractions $L$;
let $K$ be the field of fractions of $A$ (and note that $A$ is integral, since $B$ is integral).
We have already seen, in the proof of [9.3](#I.9.3), that $B\otimes_A K$ is a finite product of fields;
since it is contained in $L$, it is a field;
since it contains $B$, it is equal to $L$ itself.
An element of $K$ which is integral over $A$ is integral over $B$, and is thus in $B$, since $B$ is normal, and thus also in $A$, since $B\cap K=A$ (as follows from the fact that $B$ is faithfully flat over $A$).

Now suppose that $A$ is normal;
we will prove that $B$ is also normal.
By [7.6](#I.7.6), we have that $B=B'_\frak{n}$, where $B'=A[t]/FA[t]$ (with $F$ and $\frak{n}$ being as in [7.6](#I.7.6)).
Thus $L=B\otimes_A K$ is a localisation of $B'\otimes_A K=K[t]/FK[t]$, and also a product of fields (finite separable extensions of $K$).
This latter product ($B'\otimes_A K$) is a direct factor of $B'_K$ (since each time we localise an Artinian ring (here $B'_K$) with respect to a multiplicatively stable set), and thus corresponds to a decomposition $F=F_1F_2$ in $K[t]$, with the generator of $L$ corresponding to $t$ being annihilated by $F_1$.
But, _since $A$ is normal, the $F_i$ are in $A[t]$_ (supposing that they are monic).
Note that $B\to L=B\otimes_A K$ is injective (since $A\to K$ is, since $B$ is flat over $A$), and so $F_1(u)=0$, with $u$ being the class of $t$ in $L$.
Suppose that $F$ were of minimal degree;
then it would follows that $F_2=1$.
(N.B. we would have $F'(u)=F'_1(u)F_2(u)+F_1(u)F'_2(u)=F'_1(u)F_2(u)$, since $F_1(u)=0$, whence $F'_1(u)\neq 0$ since $F'(u)\neq0$.)
Thus
$$
  L = B\otimes_A K = K[t]/FK[t]
\tag{$*$}
$$
and so $F$ is a separable polynomial in $K[T]$ (but evidently not necessarily in $A[t]$).
(N.B. for now, we have only shown, essentially, that we can choose $F$ and $\frak{n}$ in [7.6](#I.7.6) such that, with the above notation, $B'\to B'_\frak{n}=B$ is _injective_;
for this, we have used the fact that $A$ is normal;
I do not know if this remains true without this normality hypothesis).
:::

Now recall the well-known lemma, taken from Serre's lectures last year:

::: {.itenv #I.9.6 title="Lemma 9.6"}
Let $K$ be a ring, $F\in K[t]$ a separable monic polynomial, $L=K[t]/FK[t]$, and $u$ the class of $t$ in $L$ (so that $F'(u)$ is an invertible element of $L$).
Then
$$
  \tr_{L/K} u^i/F'(u) =
  \begin{cases}
    0 &\text{if }0\leq i<n-1\text{;}
  \\1 &\text{if }i=n-1
  \end{cases}
$$
where $n=\deg F$.
:::

::: {.itenv #I.9.7 title="Corollary 9.7"}
The determinant of the matrix $(u^j\cdot u^i/F'(u))_{0\leq i,j\leq n-1}$ is equal to $(-1)^{n(n-1)/2}$, and thus invertible in every sub-ring $A$ of $K$.
:::

::: {.itenv #I.9.8 title="Corollary 9.8"}
Let $A$ be a sub-ring of $K$, $V$ the $A$-module generated by the $u^i$ (for $0\leq i\leq n-1$), and $V'$ the sub-$A$-module of $L$ consisting of the $x\in L$ such that $\tr_{L/K}(xy)\in A$ for all $y\in V$ (i.e. for $y$ of the form $u^i$, for $0\leq i\leq n-1$).
Then $V'$ is the $A$-module given by the basis $u^i/F'(u)$ (for $0\leq i\leq n-1$).
:::

::: {.itenv #I.9.9 title="Corollary 9.9"}
Suppose that $K$ is the field of fractions of an integral normal ring $A$, with the coefficients of $F$ lying in $A$.
Then, with the notation of [9.8](#I.9.8), $V'$ contains the normal closure $A'$ of $A$ in $L$, which is thus contained in $A[u]/F'(u)$, and a fortiori in $A[u][F'(u)^{-1}]$.
:::

We can apply the above corollary to the situation that we have obtained in the proof: since $F'(u)$ is invertible in $B$, and since $B$ contains $A[u]$, $B$ contains $A'$.
By the Main Theorem (or by the fact that $B=A[u]_\frak{n}$), $B$ is a localisation of $A'$.
Since $A'$ is normal, so too is $B$.

::: {.proof}
_(of ii)._
We proceed as in the above proof to show that we can choose $F$ in [7.6](#I.7.6) such that we again have ($*$).
The only obstacle a priori is that we can no longer prove that $B\to L$ is injective, since $B$ is no longer assumed to be flat over $A$, and so we can only apply the same argument a priori to the image $B_1$ of $B$ under the aforementioned homomorphism.
It immediately follows that $B_1$ is flat over $A$ (since it is the localisation of a free $A$-algebra).
By [4.8](#I.4.8), the morphism $B\to B_1$ is étale, and thus an isomorphism, which finishes the proof.
:::

(From an editorial point of view, we should perform the two proofs above, and place the formal calculations of the lemma and of its corollaries in a separate section).

::: {.itenv #I.9.10 title="Corollary 9.10"}
Let $f\colon X\to Y$ be an étale morphism.
If $Y$ is normal, then $X$ is normal;
the converse is true if $f$ is surjective.
:::

::: {.itenv #I.9.11 title="Corollary 9.11"}
Let $f\colon X\to Y$ be a dominant morphism, with $Y$ normal and $X$ connected.
If $f$ is unramified, then it is also étale, and $X$ is then normal and thus irreducible (since it is connected).
:::

::: {.proof}
Let $U$ be the set of points where $f$ is étale.
Since $U$ is open, it suffices to show that it is also closed and non-empty.
Since $U$ contains the inverse image of the generic point of $Y$ (recall that, for an algebra over a field, unramified = étale), it is non-empty (since $X$ dominates $Y$).
If $x$ belongs to the closure of $U$, then it belongs to the closure of an irreducible component $U_i$ of $U$, and thus to an irreducible component $X_i=\overline{U_i}$ of $X$ which intersects $U$ and which thus dominates $Y$ (since every component of $U$, being flat over $Y$, dominates $Y$).
Then, if $y$ is the projection of $x$ over $Y$, $\cal{O}_y\to\cal{O}_x$ is _injective_ (taking into account the fact that $\cal{O}_y$ is integral).
Since $\cal{O}_y$ is normal and $\cal{O}_y\to\cal{O}_x$ is unramified, we conclude with the help of [9.5 (ii)](#I.9.5).
:::

::: {.itenv #I.9.12 title="Corollary 9.12"}
Let $f\colon X\to Y$ be a dominant morphism of finite type, with $Y$ normal and $X$ irreducible.
Then the set of points where $f$ is étale is identical to the complement of the support of $\Omega_{X/Y}^1$, i.e. to the complement of the sub-prescheme of $X$ defined by the different ideal $\frak{d}_{X/Y}$.
:::

(This is the "less trivial" statement which was alluded to in the remark in §4.)

::: {.rmenv title="Remark"}
We do not claim that a connected étale covering of an irreducible scheme is itself irreducible if we do not assume the base to be normal.
This question will be studied in §11.
:::
